### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Raycoms** [cweckerl/simplefarming#56]
**Forge Version**
forge-1.14.4-28.1.116.jar

**Log file (optional)**

java.lang.IllegalArgumentException: Unsupported mob type for TemptGoal
	at net.minecraft.entity.ai.goal.TemptGoal.<init>(SourceFile:39) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at enemeez.simplefarming.entities.ai.MoreTemptation.<init>(MoreTemptation.java:9) ~[?:1.14.4-1.2.7] {re:classloading}
	at enemeez.simplefarming.events.TemptationTask.onEntitySpawn(TemptationTask.java:40) ~[?:1.14.4-1.2.7] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_483_TemptationTask_onEntitySpawn_EntityJoinWorldEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraft.world.server.ServerWorld.func_217440_f(ServerWorld.java:904) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ChunkManager.lambda$null$24(ChunkManager.java:577) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[?:?] {re:classloading}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[?:?] {re:classloading}
	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ChunkManager.lambda$func_219200_b$25(ChunkManager.java:554) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616) ~[?:1.8.0_232] {}
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591) ~[?:1.8.0_232] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_232] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213168_p(SourceFile:550) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider.func_212849_a_(SourceFile:135) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.chunk.AbstractChunkProvider.func_217205_a(SourceFile:16) ~[?:?] {re:classloading}
	at net.minecraft.world.World.func_175674_a(World.java:967) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.IEntityReader.func_72839_b(SourceFile:34) ~[?:?] {re:classloading}
	at net.minecraft.world.IEntityReader.func_223439_a(SourceFile:64) ~[?:?] {re:classloading}
	at net.minecraft.world.IWorld.func_223439_a(IWorld.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.entity.Entity.func_213306_e(Entity.java:691) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Entity Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.entity.Entity.func_213315_a(Entity.java:494) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Entity Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_213352_e(LivingEntity.java:1829) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.player.PlayerEntity.func_213352_e(PlayerEntity.java:1453) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2214) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.player.PlayerEntity.func_70636_d(PlayerEntity.java:494) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2032) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:365) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:183) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches ServerPlayNetHandler Transformer}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:228) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:324) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232] {}

**Describe the issue**

Server crashing when a certain user logs in, might be related to cherry trees or item pickup.

**Comment by enemeez** [comment]
It is related to tempting a mob (i.e. holding an item in your hand and attracting animals). I'll check it out this weekend.

**Comment by EternalShadow17** [comment]
im getting this same crash on my 1.16.4 server
