### ISSUE TITLE
[1.14.4-1.2.8]

### ISSUE THREAD

**Issue by KittenKoder** [cweckerl/simplefarming#71]
**Forge Version**
28.2.0

**Mod list (optional)**
Known affected mod: Silent Gear

**Log file (optional)**
[Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_51]
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_51]
	at enemeez.simplefarming.events.harvest.CropHarvest.onCropHarvest(CropHarvest.java:76) ~[?:1.14.4-1.2.8]
	at net.minecraftforge.eventbus.ASMEventHandler_397_CropHarvest_onCropHarvest_RightClickBlock.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:782) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:313) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:847) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$7203/149685392.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:699) [?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:693) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:678) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:626) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[10Mar2020 23:08:24.128] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Index: 0, Size: 0
	Index: 14
	Listeners:
		0: HIGH
		1: ASM: tschipp.carryon.common.event.ItemEntityEvents@4512b9d3 onBlockClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		2: NORMAL
		3: net.minecraftforge.eventbus.EventBus$$Lambda$2003/2062492091@1747e231
		4: net.minecraftforge.eventbus.EventBus$$Lambda$2003/2062492091@26b6462c
		5: ASM: class com.stal111.valhelsia_structures.event.PlayerInteractBlockListener onPlayerInteractBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		6: ASM: class vazkii.patchouli.client.handler.MultiblockVisualizationHandler onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		7: ASM: class vazkii.patchouli.client.handler.BookRightClickHandler onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		8: ASM: class its_meow.betteranimalsplus.common.CommonEventHandler onBlockActivate(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		9: ASM: class net.silentchaos512.gear.event.ToolBlockPlaceHandler onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		10: ASM: class tschipp.carryon.common.event.ItemEvents onBlockRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		11: ASM: enemeez.simplefarming.events.DoubleCropBreak@1f196ad6 onCropRightClicked(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		12: ASM: enemeez.simplefarming.events.harvest.BerryBushHarvest@59115b4a onCropHarvest(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		13: ASM: enemeez.simplefarming.events.harvest.CactusCropHarvest@49938e39 onCropHarvest(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		14: ASM: enemeez.simplefarming.events.harvest.CropHarvest@6ceb1a32 onCropHarvest(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		15: ASM: enemeez.simplefarming.events.harvest.DoubleCropHarvest@4f018fe6 onCropHarvest(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		16: ASM: enemeez.simplefarming.events.harvest.FruitLeavesHarvest@7ca6fe62 onCropHarvest(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		17: ASM: enemeez.simplefarming.events.harvest.GrapeHarvest@1534790a onCropHarvest(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		18: ASM: enemeez.simplefarming.events.harvest.WildPlantHarvest@31baa8dc onCropHarvest(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		19: ASM: com.legacy.moolands.MoolandsEvents@24d29fd0 onMakePortal(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		20: ASM: tschipp.carryon.common.capabilities.event.PositionCommonEvents@235cf6b0 onBlockRight(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		21: ASM: chanceCubes.listeners.BlockListener@36ee7bf onBlockInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		22: ASM: org.jwaresoftware.mcmods.vfp.misc.FluidSourceInteractionHandler@7715bccf onRightClickFluidSource(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at enemeez.simplefarming.events.harvest.CropHarvest.onCropHarvest(CropHarvest.java:76)
	at net.minecraftforge.eventbus.ASMEventHandler_397_CropHarvest_onCropHarvest_RightClickBlock.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:782)
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:313)
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:847)
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36)
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10)
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21)
	at net.minecraft.network.PacketThreadUtil$$Lambda$7203/149685392.run(Unknown Source)
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:699)
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:693)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103)
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:678)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:626)
	at java.lang.Thread.run(Thread.java:745)

**Describe the issue**
Causes Java exception when right clicking on wild flax, which isn't on farmland but is harvestable by breaking it. In singleplayer this just outputs to the debug log, untested in multipplayer.

**Comment by Lythom** [comment]
Hello,
in case it can help, I got a very similar issue (same exception, same line) by auto-mealing+harvesting potatoes with 2 Deployers from the create mod. 

Full crash log here :
[crash-2020-05-17_22.12.58-server.txt](https://github.com/enemeez/simplefarming/files/4640952/crash-2020-05-17_22.12.58-server.txt)

It corrupted the world and I had to restore a previous backup so it got pretty bad for me :'(

Thanks for your work on the mod!
