### ISSUE TITLE
CTD before Forge loads

### ISSUE THREAD

**Issue by nepphhh** [cweckerl/simplefarming#95]
Forge 32.0.75. NPE before the Forge loader takes over. Report below.

```
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 7/26/20 10:51 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at net.minecraft.client.renderer.color.BlockColors.func_186722_a(BlockColors.java:97) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at enemeez.simplefarming.client.LeavesColors.leavesColors(LeavesColors.java:18) ~[?:1.16.1-1.3.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_119_LeavesColors_leavesColors_Block.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168) ~[?:32.0] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:260) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader$$Lambda$4180/1697588954.accept(Unknown Source) ~[?:?] {}
	at java.util.HashMap.forEach(HashMap.java:1280) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:219) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:260) ~[?:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.onBlockColorsInit(ForgeHooksClient.java:165) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.color.BlockColors.func_186723_a(BlockColors.java:76) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:449) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.1-32.0.75.jar:32.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$482/894844492.call(Unknown Source) [forge-1.16.1-32.0.75.jar:32.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {re:classloading}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.color.BlockColors.func_186722_a(BlockColors.java:97)
	at enemeez.simplefarming.client.LeavesColors.leavesColors(LeavesColors.java:18)
	at net.minecraftforge.eventbus.ASMEventHandler_119_LeavesColors_leavesColors_Block.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168)
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:260)
	at net.minecraftforge.fml.ModLoader$$Lambda$4180/1697588954.accept(Unknown Source)
	at java.util.HashMap.forEach(HashMap.java:1280)
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:219)
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:260)
	at net.minecraftforge.client.ForgeHooksClient.onBlockColorsInit(ForgeHooksClient.java:165)
	at net.minecraft.client.renderer.color.BlockColors.func_186723_a(BlockColors.java:76)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:449)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$482/894844492.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 300900696 bytes (286 MB) / 599908352 bytes (572 MB) up to 6429081600 bytes (6131 MB)
	CPUs: 12
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.1-32.0.75.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.75.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.1-32.0.75.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.75.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.1-32.0.75.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
	FML: 32.0
	Forge: net.minecraftforge:32.0.75
	FML Language Providers: 
		javafml@32.0
		minecraft@1
	Mod List: 
		Ma-Enchants-1.16.1-3.2.1.jar Ma Enchants {ma-enchants@1.16.1-3.2.1 CREATE_REGISTRIES}
		TrashSlot_1.16.1-12.0.1.jar TrashSlot {trashslot@12.0.1 CREATE_REGISTRIES}
		torchslabmod-1.16.1_v1.6.16.jar Torch Slab Mod {torchslabmod@1.6.16 CREATE_REGISTRIES}
		teleportmod_1.16.1-1.1.2.jar Teleports++ {teleportmod@1.1.2 CREATE_REGISTRIES}
		NetherPortalFix_1.16.1-7.0.0.jar NetherPortalFix {netherportalfix@7.0.0 CREATE_REGISTRIES}
		zombiehs_1.16-2.4.jar Zombie Horse Spawn {zombiehs@2.4 CREATE_REGISTRIES}
		elenaidodge-1.16.1-1.7.1.jar Elenai Dodge {elenaidodge@1.16.1-1.7.1 CREATE_REGISTRIES}
		HappyTrails-1.16.1-1.0.0.3.jar Happy Trails Mod {ht@1.0.0.3 CREATE_REGISTRIES}
		Abnormals-Core-1.16.1-v2.0.0.jar Abnormals Core {abnormals_core@2.0.0 CREATE_REGISTRIES}
		Berry-Good-1.16.1-3.0.0.jar Berry Good {berry_good@3.0.0 CREATE_REGISTRIES}
		Tiny-Coal-1.16.1-1.0.0.jar Tiny Coal {tinycoal@1.0.0 CREATE_REGISTRIES}
		placeableblazerods_1.16-1.0.jar Placeable Blaze Rods {placeableblazerods@1.0 CREATE_REGISTRIES}
		KleeSlabs_1.16.1-9.0.0.jar KleeSlabs {kleeslabs@9.0.0 CREATE_REGISTRIES}
		skeletonhs_1.16-1.3.jar Skeleton Horse Spawn {skeletonhs@1.3 CREATE_REGISTRIES}
		guildedarmor-1.16.1-1.0.1.jar Gilded Armor {gildedarmor@1.0.1 CREATE_REGISTRIES}
		Extra-Boats-1.16.1-1.4.0.jar Extra Boats {extraboats@1.4.0 CREATE_REGISTRIES}
		BetterCaves-1.16.1-1.0.jar YUNG's Better Caves {bettercaves@1.16.1-1.0 CREATE_REGISTRIES}
		Waystones_1.16.1-7.0.2.jar Waystones {waystones@7.0.2 CREATE_REGISTRIES}
		PassableFoliage-1.16.1-2.0.1.jar Passable Foliage {passablefoliage@2.0.1 CREATE_REGISTRIES}
		XaerosWorldMap_1.7.4_Forge_1.16.1.jar Xaero's World Map {xaeroworldmap@1.7.4 CREATE_REGISTRIES}
		NetheriteOre-1.0.0.jar Netherite Ore {netheriteore@1.0.0 - 1.16.1 CREATE_REGISTRIES}
		DungeonCrawl-1.16.1-2.0.1.jar Dungeon Crawl {dungeoncrawl@2.0.1 CREATE_REGISTRIES}
		snowundertrees-1.16.1-v1.1.1.jar Snow Under Trees {snowundertrees@v1.1.1 CREATE_REGISTRIES}
		guardvillagers-1.16.1-1.1.1.jar Guard Villagers {guardvillagers@1.1.1 CREATE_REGISTRIES}
		bottleyourxp_1.16-1.3.jar Bottle Your Xp {bottleyourxp@1.3 CREATE_REGISTRIES}
		randompatches-1.16.1-1.22.1.0.jar RandomPatches {randompatches@1.16.1-1.22.1.0 CREATE_REGISTRIES}
		BetterHurtTimer-1.16.1-3.3.0.1.jar Better Hurt Timer {betterhurttimer@1.16.1-3.3.0.1 CREATE_REGISTRIES}
		mcw-doors-1.0.0-mc1.16.1.jar Macaw's Doors {mcwdoors@1.0.0 CREATE_REGISTRIES}
		bedspreads-FORGE-1.16.1-4.0.jar Bedspreads {bedspreads@FORGE-1.16.1-4.0 CREATE_REGISTRIES}
		environmentalcreepers-forge-1.16.1-1.6.1.jar Environmental Creepers {environmentalcreepers@1.6.1 CREATE_REGISTRIES}
		spidersprwebs_1.16-1.1.jar Spiders Produce Webs {spidersprwebs@1.1 CREATE_REGISTRIES}
		fixedanvilrepaircost_1.16-1.1.jar Fixed Anvil Repair Cost {fixedanvilrepaircost@1.1 CREATE_REGISTRIES}
		huskspawn_1.16-1.1.jar Husk Spawn {huskspawn@1.1 CREATE_REGISTRIES}
		forge-1.16.1-32.0.75-universal.jar Forge {forge@32.0.75 CREATE_REGISTRIES}
		Waddles-1.16.1-0.8.7.jar Waddles {waddles@1.16.1-0.8.7 CREATE_REGISTRIES}
		Bones-1.16.1-1.3.2.jar Bones {bones@1.16.1-1.3.2 CREATE_REGISTRIES}
		absentbydesign-1.16.1-1.1.0.jar Absent By Design Mod {absentbydesign@1.16.1-1.1.0 CREATE_REGISTRIES}
		dash-1.16.1-1.0.1.jar Dash {dash@1.0.1 CREATE_REGISTRIES}
		structure-gel-api-1.16.1-1.1.1.jar Structure Gel API {structure_gel@1.1.1 CREATE_REGISTRIES}
		forge-1.16.1-32.0.75-client.jar Minecraft {minecraft@1.16.1 CREATE_REGISTRIES}
		GentleFawn-1.0.4-MC1.16.1.jar Gentle Fawn {gentlefawn@1.0.4 CREATE_REGISTRIES}
		netherportalspread_1.16-3.5.jar Nether Portal Spread {netherportalspread@3.5 CREATE_REGISTRIES}
		nccreepers_1.16-1.2.jar Naturally Charged Creepers {nccreepers@1.2 CREATE_REGISTRIES}
		EasierSleeping-1.16.1-1.0.1.jar Easier Sleeping {easier_sleeping@1.0.1 CREATE_REGISTRIES}
		BiomesOPlenty-1.16.1-11.0.0.390-universal.jar Biomes O' Plenty {biomesoplenty@1.16.1-11.0.0.390 CREATE_REGISTRIES}
		valhelsia_structures-16.0.1.jar Valhelsia Structures {valhelsia_structures@16.0.1 CREATE_REGISTRIES}
		dungeons-plus-1.16.1-1.0.2.jar Dungeons Plus {dungeons_plus@1.0.2 CREATE_REGISTRIES}
		edibles_1.16-1.1.jar Edibles {edibles@1.1 CREATE_REGISTRIES}
		simplefarming-1.16.1-1.3.1.jar Simple Farming {simplefarming@1.16.1-1.3.1 CREATE_REGISTRIES}
		corpsecomplex-FORGE-1.16.1-3.0.jar Corpse Complex {corpsecomplex@FORGE-FORGE-1.16.1-3.0 CREATE_REGISTRIES}
		Xaeros_Minimap_20.17.0_Forge_1.16.1.jar Xaero's Minimap {xaerominimap@20.17.0 CREATE_REGISTRIES}
		rndbmflowers_1.16-1.2.jar Random Bone Meal Flowers {rndbmflowers@1.2 CREATE_REGISTRIES}
		gravestone-1.16.1-1.0.3.jar Gravestone Mod {gravestone@1.16.1-1.0.3 CREATE_REGISTRIES}
		collective-1.16.1-1.35.jar Collective {collective@1.35 CREATE_REGISTRIES}
		lava-monster-1.16.1-1.0.7.jar Lava Monster {lava_monster@1.0.7 CREATE_REGISTRIES}
		AutoRegLib-1.6-42.jar AutoRegLib {autoreglib@1.6-42 CREATE_REGISTRIES}
		Quark-r2.2-255.jar Quark {quark@r2.2-255 CREATE_REGISTRIES}
		Enhanced-Mushrooms-1.16.1-v2.0.4.jar Enhanced Mushrooms {enhanced_mushrooms@2.0.0 CREATE_REGISTRIES}
		WorldPreGenerator-1.16.1-1.0.1.jar World Pre Generator {world_pre_generator@1.0.1 CREATE_REGISTRIES}
		DoubleSlabs-1.16-3.2.0.jar Double Slabs {doubleslabs@3.2.0 ERROR}
		backpacked-1.4.4-1.16.1.jar Backpacked {backpacked@1.4.4 CREATE_REGISTRIES}
		AmbientEnvironment-4.0.0.1.jar Ambient Environment {ambientenvironment@4.0.0.1 CREATE_REGISTRIES}
		AppleSkin-mc1.16.1-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 CREATE_REGISTRIES}
		AI-Improvements-1.16.1-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 CREATE_REGISTRIES}
		almostalltheores-3.0.0.2.jar Almost All the Ores {almostalltheores@3.0.0.2 CREATE_REGISTRIES}
		SakuraRosea-1.5.1-MC1.16.1.jar Sakura Rosea {sakurarosea@1.5.1 CREATE_REGISTRIES}
		BetterBurning-1.16.1-2.0.2.jar BetterBurning {betterburning@2.0.2 CREATE_REGISTRIES}
		strayspawn_1.16-1.1.jar Stray Spawn {strayspawn@1.1 CREATE_REGISTRIES}
		grindstonesharpertools_1.16-1.4.jar Grindstone Sharper Tools {grindstonesharpertools@1.4 CREATE_REGISTRIES}
		FastLeafDecay-v23.jar FastLeafDecay {fastleafdecay@v23 CREATE_REGISTRIES}
		PrettyBeaches_1.16.1-5.0.0.jar Pretty Beaches {prettybeaches@5.0.0 CREATE_REGISTRIES}
		BetterMineshaftsForge-1.16.1-1.3.jar YUNG's Better Mineshafts {bettermineshafts@1.16.1-1.3 CREATE_REGISTRIES}
	Launched Version: 1.16.1-forge-32.0.75
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Radeon RX 570 Series GL version 4.6.13558 Compatibility Profile Context 26.20.11016.1, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 12x AMD Ryzen 5 1600 Six-Core Processor 
```

**Comment by nepphhh** [comment]
Appears to be some sort of conflict with SakuraRosea. Removing it allows MC to load into Forge & load normally after that. Biomes O' Plenty interaction may also be involved; untested.
